# app/models_seo.py
from datetime import datetime
from app import db


class SEOHealthSnapshot(db.Model):
    """One row per monitoring run per site. Stores key health metrics for trending."""
    __tablename__ = "seo_health_snapshots"
    __table_args__ = {"extend_existing": True}

    id              = db.Column(db.Integer, primary_key=True)
    site_id         = db.Column(db.Integer, nullable=True)   # wp_sites.id (nullable — URL-only sites)
    account_id      = db.Column(db.Integer, nullable=True)
    site_url        = db.Column(db.String(512), nullable=False)

    # Technical health
    health_score        = db.Column(db.Integer, default=0)
    sitemap_ok          = db.Column(db.Boolean, default=True)
    robots_ok           = db.Column(db.Boolean, default=True)
    homepage_status     = db.Column(db.Integer, default=200)
    broken_links_count  = db.Column(db.Integer, default=0)

    # GSC snapshot (null if GSC not connected)
    gsc_clicks          = db.Column(db.Integer, nullable=True)
    gsc_impressions     = db.Column(db.Integer, nullable=True)
    gsc_avg_position    = db.Column(db.Float, nullable=True)

    # Full raw data blob for diffing
    data        = db.Column(db.JSON, nullable=True)
    created_at  = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)


class SEOAlert(db.Model):
    """An alert generated by the monitoring engine for a site/account."""
    __tablename__ = "seo_alerts"
    __table_args__ = {"extend_existing": True}

    id          = db.Column(db.Integer, primary_key=True)
    site_id     = db.Column(db.Integer, nullable=True)
    account_id  = db.Column(db.Integer, nullable=True)
    site_url    = db.Column(db.String(512), nullable=True)

    # alert_type: traffic_drop | ranking_drop | sitemap_error | robots_blocked |
    #             homepage_error | health_score_drop | broken_links | new_404s
    alert_type  = db.Column(db.String(64), nullable=False)
    severity    = db.Column(db.String(16), nullable=False)   # critical | warning | info
    message     = db.Column(db.Text, nullable=False)
    detail      = db.Column(db.JSON, nullable=True)          # extra structured context

    is_read     = db.Column(db.Boolean, default=False, nullable=False)
    created_at  = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
